---
abstract: 'Subclass of Module::Build which removes the old module before installing the new one'
author:
  - 'Joel A. Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-CleanInstall
no_index:
  directory:
    - examples
    - t
  file:
    - README.pod
provides:
  Module::Build::CleanInstall:
    file: lib/Module/Build/CleanInstall.pm
    version: 0.01
requires:
  Module::Build: 0.36
  parent: 0
  perl: v5.8.1
resources:
  bugtracker: http://github.com/jberger/Module-Build-CleanInstall/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Module-Build-CleanInstall
version: 0.01
